### ISSUE TITLE
Create a Short URL

### ISSUE THREAD

**Issue by wildintellect** [cloudnativegeo/cloud-optimized-geospatial-formats-guide#46]
The URL is a little long. DevelopmentSeed has an internal S3 based link shortening service. We should register a shortname for ds.io and use that for Slides etc to make it easier for people to get to.

Any shortname suggestions?

**Comment by kylebarron** [comment]
> Any shortname suggestions?

Maybe `ds.io/co-formats`?

**Comment by zacharyDez** [comment]
^+1! I prefer `cloud-formats`. It's more obvious than the `co` acronym.

**Comment by kylebarron** [comment]
I also think the full URL can be shorter. Maybe the repo name could be just `cloud-formats-guide`? If it's on `developmentseed.org`, `geospatial` can probably be inferred. And `cloud` instead of `cloud-optimized` might be fine for the URL itself?

**Comment by kylebarron** [comment]
I think by default the url is always the same as the repo name. You might be able to change that with a CNAME file?

**Comment by wildintellect** [comment]
The point of the short url is partly so we don't have to rename the repo just yet. We can always update the redirect.
CNAME might only be read if direct DNS is configured on the repo. Since we might be moving the content soonish, let just push ahead as is.

**Comment by zacharyDez** [comment]
@wildintellect, do we want the URL shortened before merging #51? Not sure if there are other blockers there.

**Comment by zacharyDez** [comment]
URL is set to [guide.cloudnativegeo.org](https://guide.cloudnativegeo.org/)
