### ISSUE TITLE
Docs vs _site for storing the generated Website.

### ISSUE THREAD

**Issue by wildintellect** [cloudnativegeo/cloud-optimized-geospatial-formats-guide#58]
I ran into an issue, when I generate a local preview of the site it now uses the `docs` folder, and since this folder is not ignored (.gitignore) my local copy wants to be committed to git.

What we had previously was that _site was generated, but on github this was only ever in a gh-pages branch. So the actual website files would never end up in the main and accidentally be direct edited, pushed, or pull. 

I'm not sure what the typical layout is for `quarto` sites on github (the template we use is _stite only in gh-pages).

Suggestions @jedsundwall @abarciauskas-bgse @kylebarron

**Comment by kylebarron** [comment]
I agree; I mentioned in https://github.com/cloudnativegeo/cloud-optimized-geospatial-formats-guide/pull/55#discussion_r1324718171 that I was confused that `docs` was committed to git.

My preference would be to revert to only storing the built form of the docs on the `gh-pages` branch

**Comment by jedsundwall** [comment]
@kylebarron @wildintellect I think I've figured this out and gone back to how you'd had it configured before. Thanks for pointing me in the right direction. Previews appear to work and deploying to the `gh-pages` branch seems to work properly now.

**Comment by wildintellect** [comment]
Do we plan to remove the `docs` from the main branch then?

**Comment by jedsundwall** [comment]
Yes, #55 will remove `docs` from the main branch when merged.

**Comment by kylebarron** [comment]
https://guide.cloudnativegeo.org/ appears to no longer be served correctly.

**Comment by kylebarron** [comment]
Closing this as fixed in https://github.com/cloudnativegeo/cloud-optimized-geospatial-formats-guide/pull/61, which moved the built website back to `_site`
