### ISSUE TITLE
Clean up Merged Branches

### ISSUE THREAD

**Issue by wildintellect** [cloudnativegeo/cloud-optimized-geospatial-formats-guide#59]
We should remove any stale branches that aren't actively being worked on. I assume most belong to @abarciauskas-bgse and @kylebarron do you want to trim yourself or I can go through on Monday and do it?

**Comment by abarciauskas-bgse** [comment]
I cleaned mine up!

**Comment by kylebarron** [comment]
I cleaned up mine as well. I'm also in favor of checking this box in the settings:
<img width="549" alt="image" src="https://github.com/cloudnativegeo/cloud-optimized-geospatial-formats-guide/assets/15164633/71b61d6b-6881-4652-bcea-7cd821cdadf1">
(I don't have permissions to do that)

**Comment by wildintellect** [comment]
Thanks @kylebarron I enabled that feature. Look like we're down to 6 active branches, closing !!!
